/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CustomInput: typeof import('./src/components/UI/CustomInput.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElImput: typeof import('element-plus/es')['ElImput']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElText: typeof import('element-plus/es')['ElText']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    HeaderComponent: typeof import('./src/components/HeaderComponent.vue')['default']
    HomePageCenterComponent: typeof import('./src/components/HomePageCenterComponent.vue')['default']
    HomePageLeftSideComponent: typeof import('./src/components/HomePageLeftSideComponent.vue')['default']
    HomePageRightComponent: typeof import('./src/components/HomePageRightComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TotalTime: typeof import('./src/components/UI/TotalTime.vue')['default']
  }
}
